- .github/workflows/release.yaml
Signed-off-by: zyy17 <zyylsxm@gmail.com>
> ci: add 'workflow_dispatch' in release

- charts/greptimedb/templates/greptimedb/cluster.yaml
- charts/greptimedb/values.yaml
1. split greptimedb image to registry, repository and tag
2. define enablePrometheusMonitor int the value.yaml
3. use toYaml to get request and limit
> refactor: refine greptimedb config struct

- charts/greptimedb-operator/Chart.yaml
- charts/greptimedb-operator/crds/greptimedbcluster.yaml
- charts/greptimedb-operator/values.yaml
Signed-off-by: zyy17 <zyylsxm@gmail.com>
> chore: update operator crds and version

- charts/greptimedb-operator/Chart.yaml
- charts/greptimedb-operator/templates/clusterrole.yaml
Releated PR: https://github.com/GreptimeTeam/greptimedb-operator/pull/112.
> chore: add necessary rbac of operator

- .github/scripts/release-charts-to-s3.sh
- .github/workflows/release.yaml
After the charts releasing, we also release the latest charts to S3.
> ci: release greptime charts to s3

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/templates/NOTES.txt
- charts/greptimedb-cluster/templates/cluster.yaml
- charts/greptimedb-cluster/values.yaml
- charts/greptimedb-operator/Chart.yaml
- charts/greptimedb-operator/README.md
- charts/greptimedb-operator/crds/greptimedbcluster.yaml
- charts/greptimedb-operator/values.yaml
1. update greptimedb-operator version to 0.1.0-alpha.20.
2. add `reloadWhenConfigChange`, `storeKeyPrefix` configure.
> chore: update operator version

- README.md
- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/README.md.gotmpl
- charts/greptimedb-cluster/templates/cluster.yaml
- charts/greptimedb-cluster/templates/secret.yaml
- charts/greptimedb-cluster/templates/serviceaccount.yaml
- charts/greptimedb-cluster/values.yaml
Set object storage secretName is `{{ .Release.Name }}-secret`, unnecessary set this field every time.
> refactor(greptimedb-cluster): rename object storage secretName

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/values.yaml
wait for https://github.com/GreptimeTeam/helm-charts/pull/114 merge
> chore(greptimedb-cluster): not set resource requests and limits in pod template

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/templates/cluster.yaml
- charts/greptimedb-cluster/values.yaml
- charts/greptimedb-operator/Chart.yaml
- charts/greptimedb-operator/README.md
- charts/greptimedb-operator/crds/greptimedbclusters.yaml
- charts/greptimedb-operator/crds/greptimedbstandalones.yaml
- charts/greptimedb-operator/values.yaml
- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
- charts/greptimedb-standalone/templates/service.yaml
- charts/greptimedb-standalone/templates/statefulset.yaml
- charts/greptimedb-standalone/values.yaml
Upstream PR: https://github.com/GreptimeTeam/greptimedb-operator/pull/151
> chore: remove opentsdb port

- charts/greptimedb-operator/Chart.yaml
- charts/greptimedb-operator/README.md
- charts/greptimedb-operator/README.md.gotmpl
- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
> docs(helm): Update CRD upgrade instructions in Helm documentation

- .github/pr-title-checker-config.json
- .github/workflows/pr-title-checker.yaml
Support the title of describing breaking changes, for example:
> refactor!: xxxx
> ci: support the title of describing breaking changes

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/values.yaml
- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
- charts/greptimedb-standalone/values.yaml
> chore: upgade greptimedb to v0.14.0

- Makefile
- charts/greptimedb-cluster/Chart.yaml
- scripts/update/update-version.sh
`update-chart` -> `update-version`
Not only update the chart, also update the image version.
> chore: rename update chart script

- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
- charts/greptimedb-standalone/templates/NOTES.txt
- charts/greptimedb-standalone/templates/statefulset.yaml
When modify secret or configmap, greptimedb will be restart.
> feat(greptimedb-standalone): add checksum to restart the pod when the ConfigMap or Secret is changed

- docker/debug-pod/Dockerfile
Already defined in: https://github.com/GreptimeTeam/helm-charts/pull/280/files#diff-550cc8213a5ade3b9e01bca55b581ce66d3090487bd77c1828dab0b593c23e18L12
> build: Remove redundant telnet tool installation

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/templates/cluster.yaml
- charts/greptimedb-cluster/values.yaml
wait for: https://github.com/GreptimeTeam/helm-charts/pull/287
Use native field to define etcd endpoints: https://github.com/GreptimeTeam/greptimedb-operator/blob/main/apis/v1alpha1/greptimedbcluster_types.go#L159
> chore: rename `etcdEndpoints` -> `endpoints` in meta backendStorage

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/templates/NOTES.txt
- charts/greptimedb-cluster/values.yaml
wait for: https://github.com/GreptimeTeam/helm-charts/pull/283
Add check to flownode and frontend are enabled (true)
> fix: incorrect install NOTES

- docker/debug-pod/Dockerfile
Fixed to: https://github.com/GreptimeTeam/helm-charts/actions/runs/15482274379/job/43590170432
> build: failed to build helm tool

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/values.yaml
- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
- charts/greptimedb-standalone/values.yaml
This PR updates the GreptimeDB version.
> chore: Update GreptimeDB version to v0.15.0

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/values.yaml
- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
- charts/greptimedb-standalone/values.yaml
This PR updates the GreptimeDB version.
> chore: Update GreptimeDB version to v0.15.1

- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
- charts/greptimedb-standalone/templates/statefulset.yaml
> refactor: container args

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/values.yaml
- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
- charts/greptimedb-standalone/values.yaml
This PR updates the GreptimeDB version.
> chore: Update GreptimeDB version to v0.15.5

- charts/greptimedb-cluster/Chart.yaml
- charts/greptimedb-cluster/README.md
- charts/greptimedb-cluster/values.yaml
- charts/greptimedb-standalone/Chart.yaml
- charts/greptimedb-standalone/README.md
- charts/greptimedb-standalone/values.yaml
This PR updates the GreptimeDB version.
> chore: Update GreptimeDB version to v0.17.0

- .github/workflows/ci.yaml
related to: https://github.com/helm/kind-action?tab=readme-ov-file
> ci: update kubernetes version to v1.32.0
